version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www:cached
    ports:
      - "8080:80"
    networks:
      - webnet

  database:
    image: mysql
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATABASE: talent
      MYSQL_ROOT_PASSWORD: talent
      MYSQL_USER: talent
      MYSQL_PASSWORD: talent
    volumes:
      - /var/lib/mysql
    networks:
      - webnet

networks:
  webnet:
